title: <p align="center"> Giorgio Carbone </p>

logo: "/images/picture.jpg?raw=true"

description:
  <p align="center">
  (+39) 3406959794 |
  <br> <a href="carbone.giorgio4@gmail.com">carbone.giorgio4@gmail.com</a> |
  <br> <a href="pdf/Carbone_Giorgio_CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/giorgiocarbone/">LinkedIn</a> |
  <a href="https://github.com/giocoal">GitHub</a>
  <a href="public.tableau.com/app/profile/giorgio.carbone3907">Tableau</a>
  </p>
  
  <p align="justify">
  I am pursing Master's Degree in Data Science at University of Milano-Bicocca.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
