title: <p align="center"> Giorgio Carbone </p>

logo: "/images/picture.jpg?raw=true"

description:
  <p align="center">
  Milan, Italy
  <br> (+39) 3406959794
  <br> carbone.giorgio4@gmail.com
  <br> <a href="pdf/Carbone_Giorgio_CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/giorgiocarbone/">LinkedIn</a> |
  <a href="https://github.com/giocoal">GitHub</a> |
  <a href="public.tableau.com/app/profile/giorgio.carbone3907">Tableau</a>
  </p>
  
  <p align="justify">
  I am pursing Master's Degree in Data Science at University of Milano-Bicocca, where I’m receiving solid training in all the major fields of Data Science, like Statistics, Computer Science, Programming, Machine Learning and more.
  <br><br>
  I  have a hard science education, in fact i've earned a Bachelor's Degree in Chemical Sciences and Technologies at University of Milano-Bicocca, which program included courses in mathematics, physics, chemistry (inorganic, organic, physical and analytical).
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
